/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ebookmanager.ui;

/**
 *
 * @author trank
 */
import com.ebookmanager.model.Book;
import com.ebookmanager.service.BookProgressService;
import com.ebookmanager.service.BookService;
import com.ebookmanager.util.SessionManager;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
public class CommunityPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityPanel
     */
    private BookService bookService;
    private BookProgressService progressService;
    private MainView mainView;
    public CommunityPanel(MainView mainView) {
        this.mainView = mainView;
        this.bookService = new BookService();
        this.progressService = new BookProgressService();
        initComponents();
        customInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        pnlSearchBox = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listWrapper = new javax.swing.JPanel();
        listPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1200, 750));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout(20, 20));

        pnlTop.setOpaque(false);
        pnlTop.setPreferredSize(new java.awt.Dimension(0, 60));

        pnlSearchBox.setOpaque(false);
        pnlSearchBox.setPreferredSize(new java.awt.Dimension(450, 50));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtSearch.setPreferredSize(new java.awt.Dimension(400, 40));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        pnlSearchBox.add(txtSearch);

        btnSearch.setBackground(new java.awt.Color(52, 152, 219));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.setPreferredSize(new java.awt.Dimension(100, 40));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlSearchBox.add(btnSearch);

        btnUpload.setBackground(new java.awt.Color(204, 204, 204));
        btnUpload.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpload.setText("Upload");
        btnUpload.setPreferredSize(new java.awt.Dimension(100, 40));
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addComponent(pnlSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlTop, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(null);

        listWrapper.setBackground(new java.awt.Color(255, 255, 255));
        listWrapper.setLayout(new java.awt.BorderLayout());

        listPanel.setBackground(new java.awt.Color(255, 255, 255));
        listPanel.setLayout(new javax.swing.BoxLayout(listPanel, javax.swing.BoxLayout.Y_AXIS));
        listWrapper.add(listPanel, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(listWrapper);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void customInit() {
        
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent e) {
                loadBooks("");
            }
        });
    }

    
    private void loadBooks(String keyword) {
        listPanel.removeAll(); 
        ArrayList<Book> books;

        
        if (keyword == null || keyword.trim().isEmpty()) {
            books = bookService.findAllBooks();
        } else {
            books = bookService.searchBooks(keyword.trim());
        }

        
        if (books == null || books.isEmpty()) {
            JLabel lblEmpty = new JLabel("No books found.");
            lblEmpty.setFont(new Font("Segoe UI", Font.ITALIC, 14));
            lblEmpty.setAlignmentX(Component.CENTER_ALIGNMENT);
            lblEmpty.setBorder(new EmptyBorder(20,0,0,0));
            listPanel.add(lblEmpty);
        } else {
            listPanel.add(Box.createVerticalStrut(10)); 
            
            for (Book book : books) {
                JPanel bookRow = new JPanel(new BorderLayout());
                bookRow.setBackground(new Color(245, 245, 245)); 
                bookRow.setMaximumSize(new Dimension(Integer.MAX_VALUE, 60)); 
                bookRow.setPreferredSize(new Dimension(0, 60));
                bookRow.setBorder(new EmptyBorder(0, 20, 0, 20));
                
                bookRow.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseEntered(MouseEvent e) { bookRow.setBackground(new Color(220, 220, 220)); }
                    @Override
                    public void mouseExited(MouseEvent e) { bookRow.setBackground(new Color(245, 245, 245)); }
                    @Override
                    public void mouseClicked(MouseEvent e) { showBookDetailDialog(book); }
                });

                String displayTitle = book.getBookTitle();
                if (book.getAuthorName() != null && !book.getAuthorName().isEmpty()) {
                    displayTitle += "  -  " + book.getAuthorName();
                }
                
                JLabel lblTitle = new JLabel(displayTitle);
                lblTitle.setFont(new Font("Segoe UI", Font.PLAIN, 16));
                lblTitle.setHorizontalAlignment(SwingConstants.CENTER);
                bookRow.add(lblTitle, BorderLayout.CENTER);

                
                JPanel wrapper = new JPanel(new BorderLayout());
                wrapper.setBackground(Color.WHITE);
                wrapper.add(bookRow, BorderLayout.CENTER);
                wrapper.setBorder(new EmptyBorder(0, 10, 10, 10));
                
                listPanel.add(wrapper);
            }
        }
        
        listPanel.revalidate();
        listPanel.repaint();
    }

    
    private void showBookDetailDialog(Book book) {
        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Book Detail", true);
        dialog.setSize(500, 400); 
        dialog.setLocationRelativeTo(this);
        dialog.setLayout(new BorderLayout());
        
        JPanel content = new JPanel(new GridBagLayout());
        content.setBackground(new Color(245, 245, 245));
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.gridx = 0; gbc.gridy = 0;
        
        content.add(new JLabel("Title:"), gbc); gbc.gridx = 1;
        JTextField txtTitle = new JTextField(book.getBookTitle()); txtTitle.setEditable(false); txtTitle.setPreferredSize(new Dimension(250, 30)); content.add(txtTitle, gbc);
        
        gbc.gridx = 0; gbc.gridy = 1; content.add(new JLabel("Author:"), gbc); gbc.gridx = 1;
        JTextField txtAuthor = new JTextField(book.getAuthorName()); txtAuthor.setEditable(false); txtAuthor.setPreferredSize(new Dimension(250, 30)); content.add(txtAuthor, gbc);
        
        gbc.gridx = 0; gbc.gridy = 2; content.add(new JLabel("Publisher:"), gbc); gbc.gridx = 1;
        JTextField txtPub = new JTextField(book.getPublisher()); txtPub.setEditable(false); txtPub.setPreferredSize(new Dimension(250, 30)); content.add(txtPub, gbc);

        gbc.gridx = 0; gbc.gridy = 3; content.add(new JLabel("Genre:"), gbc); gbc.gridx = 1;
        JTextField txtGenre = new JTextField(book.getGenre()); txtGenre.setEditable(false); txtGenre.setPreferredSize(new Dimension(250, 30)); content.add(txtGenre, gbc);
        
        dialog.add(content, BorderLayout.CENTER);
        
        JPanel footer = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 15));
        footer.setBackground(new Color(245, 245, 245));
        if (SessionManager.getInstance().getCurrentUser() == null) return;
        
        int userId = SessionManager.getInstance().getCurrentUser().getUserId();
        boolean isOwned = progressService.isBookInLibrary(userId, book.getBookId());

        JButton btnReadOrPreview; 
        JButton btnAddLib = new JButton("Add to Library");
        JButton btnClose = new JButton("Close");

        if (isOwned) {
            btnReadOrPreview = new JButton("Read");
            btnAddLib.setEnabled(false);
            btnAddLib.setText("In Library");
            
            btnReadOrPreview.addActionListener(e -> {
                if(mainView != null) mainView.openReadingView(book, false); 
                dialog.dispose();
            });
        } else {
            btnReadOrPreview = new JButton("Preview");
            btnReadOrPreview.setBackground(new Color(255, 250, 205)); 
            
            btnReadOrPreview.addActionListener(e -> {
                if(mainView != null) mainView.openReadingView(book, true); 
                dialog.dispose();
            });
        }

        styleDialogButton(btnReadOrPreview); 
        styleDialogButton(btnAddLib); 
        styleDialogButton(btnClose);
        if (!isOwned) {
            btnAddLib.addActionListener(e -> {
                try {
                    progressService.addBookToLibrary(userId, book.getBookId());
                    JOptionPane.showMessageDialog(dialog, "Book added to your library!");
                    dialog.dispose();
                } catch (Exception ex) { JOptionPane.showMessageDialog(dialog, "Error: " + ex.getMessage()); }
            });
        }
        
        btnClose.addActionListener(e -> dialog.dispose());
        
        footer.add(btnReadOrPreview); footer.add(btnAddLib); footer.add(btnClose);
        dialog.add(footer, BorderLayout.SOUTH);
        dialog.setVisible(true);
    }

    
    private void showUploadDialog() {
        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Upload New Book", true);
        dialog.setSize(450, 400); 
        dialog.setLocationRelativeTo(this);
        dialog.setLayout(new GridBagLayout());
        dialog.getContentPane().setBackground(new Color(240, 240, 240));
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5); gbc.fill = GridBagConstraints.HORIZONTAL;
        
        JTextField txtTitle = new JTextField(20);
        JTextField txtAuthor = new JTextField(20);
        JTextField txtPublisher = new JTextField(20); 
        JTextField txtGenre = new JTextField(20);
        JLabel lblFile = new JLabel("No file selected");
        JButton btnBrowse = new JButton("Choose PDF...");
        final File[] selectedFile = {null};
        
        btnBrowse.addActionListener(e -> {
            JFileChooser fc = new JFileChooser();
            if (fc.showOpenDialog(dialog) == JFileChooser.APPROVE_OPTION) {
                selectedFile[0] = fc.getSelectedFile();
                lblFile.setText(selectedFile[0].getName());
            }
        });

        gbc.gridx = 0; gbc.gridy = 0; dialog.add(btnBrowse, gbc); gbc.gridx = 1; dialog.add(lblFile, gbc);
        gbc.gridx = 0; gbc.gridy = 1; dialog.add(new JLabel("Title:"), gbc); gbc.gridx = 1; dialog.add(txtTitle, gbc);
        gbc.gridx = 0; gbc.gridy = 2; dialog.add(new JLabel("Author:"), gbc); gbc.gridx = 1; dialog.add(txtAuthor, gbc);
        gbc.gridx = 0; gbc.gridy = 3; dialog.add(new JLabel("Publisher:"), gbc); gbc.gridx = 1; dialog.add(txtPublisher, gbc);
        gbc.gridx = 0; gbc.gridy = 4; dialog.add(new JLabel("Genre:"), gbc); gbc.gridx = 1; dialog.add(txtGenre, gbc);
        
        JButton btnSave = new JButton("Upload Book");
        btnSave.setBackground(new Color(52, 152, 219)); btnSave.setForeground(Color.WHITE);
        
        btnSave.addActionListener(e -> {
            if (selectedFile[0] != null) {
                try {
                    Book book = new Book(txtTitle.getText(), txtAuthor.getText(), selectedFile[0].getAbsolutePath(), txtPublisher.getText(), txtGenre.getText());
                    bookService.uploadBook(selectedFile[0], book);
                    JOptionPane.showMessageDialog(dialog, "Upload Successful!");
                    loadBooks(""); dialog.dispose();
                } catch (Exception ex) { JOptionPane.showMessageDialog(dialog, "Error: " + ex.getMessage()); }
            } else { JOptionPane.showMessageDialog(dialog, "Please select a PDF file."); }
        });
        
        gbc.gridx = 1; gbc.gridy = 5; gbc.anchor = GridBagConstraints.EAST; gbc.fill = GridBagConstraints.NONE;
        dialog.add(btnSave, gbc);
        dialog.setVisible(true);
    }

    
    private void showManageUploadsDialog() {
        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Manage My Uploads", true);
        dialog.setSize(600, 500);
        dialog.setLocationRelativeTo(this);
        dialog.setLayout(new BorderLayout());
        
        JPanel content = new JPanel();
        content.setLayout(new BoxLayout(content, BoxLayout.Y_AXIS));
        content.setBackground(new Color(240, 240, 240));
        content.setBorder(new EmptyBorder(20, 20, 20, 20));
        
        int userId = SessionManager.getInstance().getCurrentUser().getUserId();
        ArrayList<Book> myBooks = bookService.getUploadedBooks(userId); 

        if (myBooks.isEmpty()) content.add(new JLabel("No uploaded books found."));

        for (Book book : myBooks) {
            JPanel row = new JPanel(new BorderLayout());
            row.setBackground(Color.WHITE);
            row.setMaximumSize(new Dimension(Integer.MAX_VALUE, 50));
            row.setBorder(new EmptyBorder(5, 15, 5, 5));
            
            JLabel lblTitle = new JLabel(book.getBookTitle());
            lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 14));
            
            JPanel actions = new JPanel(new FlowLayout(FlowLayout.RIGHT, 5, 0));
            actions.setOpaque(false);
            
            JButton btnEdit = new JButton("Edit");
            styleDialogButton(btnEdit); btnEdit.setPreferredSize(new Dimension(70, 30));
            JButton btnDel = new JButton("Delete");
            styleDialogButton(btnDel); btnDel.setPreferredSize(new Dimension(70, 30)); btnDel.setForeground(Color.RED);
            
            btnEdit.addActionListener(e -> showEditBookDialog(dialog, book));
            btnDel.addActionListener(e -> {
                if(JOptionPane.showConfirmDialog(dialog, "Delete?", "Confirm", JOptionPane.YES_NO_OPTION) == 0) {
                    try {
                        bookService.deleteBook(book.getBookId(), SessionManager.getInstance().getCurrentUser());
                        dialog.dispose(); showManageUploadsDialog(); loadBooks(""); 
                    } catch (Exception ex) { JOptionPane.showMessageDialog(dialog, ex.getMessage()); }
                }
            });
            actions.add(btnEdit); actions.add(btnDel);
            row.add(lblTitle, BorderLayout.CENTER); row.add(actions, BorderLayout.EAST);
            content.add(row); content.add(Box.createVerticalStrut(10));
        }
        dialog.add(new JScrollPane(content), BorderLayout.CENTER);
        dialog.setVisible(true);
    }

    private void showEditBookDialog(JDialog parent, Book book) {
        JDialog dialog = new JDialog(parent, "Edit Book", true);
        dialog.setSize(400, 350);
        dialog.setLocationRelativeTo(parent);
        dialog.setLayout(new GridBagLayout());
        dialog.getContentPane().setBackground(new Color(240, 240, 240));
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10); gbc.fill = GridBagConstraints.HORIZONTAL;
        
        JTextField txtTitle = new JTextField(book.getBookTitle(), 20);
        JTextField txtAuthor = new JTextField(book.getAuthorName(), 20);
        JTextField txtPub = new JTextField(book.getPublisher(), 20); 
        JTextField txtGenre = new JTextField(book.getGenre(), 20);
        
        gbc.gridx=0; gbc.gridy=0; dialog.add(new JLabel("Title:"), gbc); gbc.gridx=1; dialog.add(txtTitle, gbc);
        gbc.gridx=0; gbc.gridy=1; dialog.add(new JLabel("Author:"), gbc); gbc.gridx=1; dialog.add(txtAuthor, gbc);
        gbc.gridx=0; gbc.gridy=2; dialog.add(new JLabel("Publisher:"), gbc); gbc.gridx=1; dialog.add(txtPub, gbc);
        gbc.gridx=0; gbc.gridy=3; dialog.add(new JLabel("Genre:"), gbc); gbc.gridx=1; dialog.add(txtGenre, gbc);
        
        JButton btnUpdate = new JButton("Update");
        btnUpdate.setBackground(new Color(52, 152, 219)); btnUpdate.setForeground(Color.WHITE);
        
        btnUpdate.addActionListener(e -> {
            book.setBookTitle(txtTitle.getText());
            book.setAuthorName(txtAuthor.getText());
            book.setPublisher(txtPub.getText());
            book.setGenre(txtGenre.getText());
            
            if (bookService.updateBook(book)) {
                JOptionPane.showMessageDialog(dialog, "Updated!");
                dialog.dispose(); parent.dispose(); showManageUploadsDialog(); loadBooks("");
            } else { JOptionPane.showMessageDialog(dialog, "Failed."); }
        });
        
        gbc.gridx=1; gbc.gridy=4; gbc.anchor = GridBagConstraints.EAST; gbc.fill = GridBagConstraints.NONE;
        dialog.add(btnUpdate, gbc);
        dialog.setVisible(true);
    }
    
    private void styleDialogButton(JButton btn) {
        btn.setPreferredSize(new Dimension(120, 35));
        btn.setFocusPainted(false);
        btn.setBackground(new Color(225, 225, 225));
        btn.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        loadBooks(txtSearch.getText());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        JPopupMenu uploadMenu = new JPopupMenu();
        JMenuItem itemNew = new JMenuItem("Upload New Book");
        itemNew.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        itemNew.setPreferredSize(new Dimension(180, 35));
        
        JMenuItem itemManage = new JMenuItem("View Uploaded Books");
        itemManage.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        itemManage.setPreferredSize(new Dimension(180, 35));
        
        itemNew.addActionListener(e -> showUploadDialog());
        itemManage.addActionListener(e -> showManageUploadsDialog());
        
        uploadMenu.add(itemNew);
        uploadMenu.add(itemManage);
        uploadMenu.show(btnUpload, 0, btnUpload.getHeight());
    }//GEN-LAST:event_btnUploadActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        loadBooks(txtSearch.getText());
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpload;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listPanel;
    private javax.swing.JPanel listWrapper;
    private javax.swing.JPanel pnlSearchBox;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
