/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ebookmanager.ui;

import com.ebookmanager.model.Book;
import com.ebookmanager.model.BookProgress;
import com.ebookmanager.model.Collection;
import com.ebookmanager.service.BookProgressService;
import com.ebookmanager.service.BookService;
import com.ebookmanager.service.CollectionService;
import com.ebookmanager.util.SessionManager;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author trank
 */
public class LibraryPanel extends javax.swing.JPanel { // ĐÃ SỬA: extends JPanel
    
    // --- KHAI BÁO BIẾN TOÀN CỤC (Class Level) ---
    private BookProgressService progressService;
    private CollectionService collectionService;
    private BookService bookService;
    private MainView mainView; 
    
    private List<Book> currentLibraryBooks = new ArrayList<>();
    private JPanel selectedPanel = null;
    private Object selectedObject = null;

    /**
     * Constructor chính: Dùng khi chạy ứng dụng
     */
    public LibraryPanel(MainView mainView) {
        this.mainView = mainView;
        
        // Khởi tạo các Service
        this.progressService = new BookProgressService();
        this.collectionService = new CollectionService();
        this.bookService = new BookService();
        
        initComponents(); // Khởi tạo giao diện kéo thả
        customInit();     // Cấu hình bổ sung
    }
    
    /**
     * Constructor mặc định: Để NetBeans không báo lỗi Design
     */
    public LibraryPanel() {
        initComponents();
    }

    private void customInit() {
        // Tăng tốc độ cuộn chuột
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        // --- THÊM ĐOẠN NÀY ĐỂ CHỈNH NÚT ---
        
        // 1. Ép kích thước chuẩn cho thanh tìm kiếm và nút Search
        Dimension dimSearchBox = new Dimension(350, 45); // Kích thước ô nhập
        Dimension dimBtnSearch = new Dimension(100, 45); // Kích thước nút Search
        
        txtSearch.setPreferredSize(dimSearchBox);
        txtSearch.setMaximumSize(dimSearchBox); // Ép không cho to hơn
        
        btnSearch.setPreferredSize(dimBtnSearch);
        btnSearch.setMaximumSize(dimBtnSearch); 
        
        // 2. Chỉnh nút Upload (Collection) cho bằng chiều cao nút Search
        Dimension dimBtnUpload = new Dimension(120, 45); // 120x45
        btnCollections.setPreferredSize(dimBtnUpload);
        
        // 3. Căn chỉnh lại Layout cho pnlSearchBox để các nút không bị lệch
        pnlSearchBox.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 0)); // FlowLayout canh trái, cách nhau 10px
        
        // --- HẾT PHẦN THÊM ---
        
        // Tự động load sách khi mở Panel này
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent e) {
                loadLibrary("");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        pnlSearchBox = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnCollections = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listWrapper = new javax.swing.JPanel();
        listPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1200, 750));
        setLayout(new java.awt.BorderLayout(20, 20));

        pnlTop.setOpaque(false);
        pnlTop.setPreferredSize(new java.awt.Dimension(0, 60));
        pnlTop.setLayout(new java.awt.BorderLayout(10, 0));

        pnlSearchBox.setOpaque(false);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtSearch.setPreferredSize(new java.awt.Dimension(250, 40));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(52, 152, 219));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.setPreferredSize(new java.awt.Dimension(100, 40));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearchBoxLayout = new javax.swing.GroupLayout(pnlSearchBox);
        pnlSearchBox.setLayout(pnlSearchBoxLayout);
        pnlSearchBoxLayout.setHorizontalGroup(
            pnlSearchBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchBoxLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSearchBoxLayout.setVerticalGroup(
            pnlSearchBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchBoxLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(pnlSearchBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlTop.add(pnlSearchBox, java.awt.BorderLayout.WEST);

        btnCollections.setBackground(new java.awt.Color(236, 240, 241));
        btnCollections.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCollections.setForeground(new java.awt.Color(44, 62, 80));
        btnCollections.setText("Collection");
        btnCollections.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        btnCollections.setContentAreaFilled(false);
        btnCollections.setOpaque(true);
        btnCollections.setPreferredSize(new java.awt.Dimension(120, 40));
        btnCollections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollectionsActionPerformed(evt);
            }
        });
        pnlTop.add(btnCollections, java.awt.BorderLayout.EAST);

        add(pnlTop, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(null);

        listWrapper.setBackground(new java.awt.Color(255, 255, 255));
        listWrapper.setLayout(new java.awt.BorderLayout());

        listPanel.setBackground(new java.awt.Color(255, 255, 255));
        listPanel.setLayout(new javax.swing.BoxLayout(listPanel, javax.swing.BoxLayout.Y_AXIS));
        listWrapper.add(listPanel, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(listWrapper);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        

    private void btnCollectionsActionPerformed(java.awt.event.ActionEvent evt) {                                               
        showCollectionMenuDialog();
    }                                              

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
        loadLibrary(txtSearch.getText());
    }                                         

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
        loadLibrary(txtSearch.getText());
    }                                         

    // --- HÀM LOGIC LOAD SÁCH ---
    private void loadLibrary(String keyword) {
        listPanel.removeAll();
        
        // Kiểm tra user đăng nhập chưa để tránh lỗi
        if (SessionManager.getInstance().getCurrentUser() == null) return;
        
        int userId = SessionManager.getInstance().getCurrentUser().getUserId();
        ArrayList<BookProgress> progresses = progressService.getBookProgresses(userId);
        currentLibraryBooks.clear();
        
        if (progresses == null || progresses.isEmpty()) {
            JLabel lbl = new JLabel("Your library is empty.", SwingConstants.CENTER);
            lbl.setFont(new Font("Segoe UI", Font.PLAIN, 14));
            lbl.setBorder(new EmptyBorder(20, 0, 0, 0));
            listPanel.add(lbl);
        } else {
            listPanel.add(Box.createVerticalStrut(10)); 
            for (BookProgress bp : progresses) {
                Book book = bp.getBookReading();
                currentLibraryBooks.add(book);

                if (!keyword.isEmpty() && !book.getBookTitle().toLowerCase().contains(keyword.toLowerCase())) {
                    continue;
                }
                
                // Tạo Panel cho từng cuốn sách
                JPanel bookCard = new JPanel(new BorderLayout(10, 0));
                bookCard.setBackground(new Color(245, 245, 245)); // Màu nền sáng hơn chút
                bookCard.setBorder(new EmptyBorder(10, 15, 10, 15));
                bookCard.setMaximumSize(new Dimension(Integer.MAX_VALUE, 70));
                bookCard.setPreferredSize(new Dimension(0, 70));

                // Thông tin sách
                JPanel infoP = new JPanel(new GridLayout(2, 1));
                infoP.setOpaque(false);
                
                JLabel lblTitle = new JLabel(book.getBookTitle());
                lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 14));
                lblTitle.setCursor(new Cursor(Cursor.HAND_CURSOR));
                lblTitle.addMouseListener(new MouseAdapter() {
                    public void mouseClicked(MouseEvent e) {
                        if(mainView != null) {
                            mainView.openReadingView(book);
                        }
                    }
                });
                
                String ratingStr = (bp.getPersonalRating() > 0) ? bp.getPersonalRating() + "/5" : "Unrated";
                JLabel lblSub = new JLabel("Page: " + bp.getCurrentPage() + "  |  Rating: " + ratingStr);
                lblSub.setFont(new Font("Segoe UI", Font.PLAIN, 12));
                lblSub.setForeground(Color.GRAY);
                
                infoP.add(lblTitle);
                infoP.add(lblSub);

                // Nút chức năng (Rate, Remove)
                JPanel actionP = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 0));
                actionP.setOpaque(false);
                
                JButton btnRate = new JButton("Rate");
                styleSmallButton(btnRate);
                btnRate.setBackground(new Color(255, 255, 200));
                
                JButton btnRemove = new JButton("Remove");
                styleSmallButton(btnRemove);
                
                btnRate.addActionListener(e -> {
                    String input = JOptionPane.showInputDialog(this, "Rate (1-5):", bp.getPersonalRating());
                    if (input != null) {
                        try {
                            int r = Integer.parseInt(input);
                            if (r >= 1 && r <= 5) {
                                progressService.rateBook(userId, book.getBookId(), r);
                                loadLibrary(txtSearch.getText());
                            }
                        } catch (Exception ex) {}
                    }
                });

                btnRemove.addActionListener(e -> {
                    int cf = JOptionPane.showConfirmDialog(this, "Remove '" + book.getBookTitle() + "'?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (cf == JOptionPane.YES_OPTION) {
                        progressService.removeBookFromLibrary(userId, book.getBookId());
                        loadLibrary(txtSearch.getText());
                    }
                });

                actionP.add(btnRate);
                actionP.add(btnRemove);

                bookCard.add(infoP, BorderLayout.CENTER);
                bookCard.add(actionP, BorderLayout.EAST);
                
                // Bọc vào wrapper để tạo khoảng cách
                JPanel wrapper = new JPanel(new BorderLayout());
                wrapper.setBackground(Color.WHITE);
                wrapper.add(bookCard, BorderLayout.CENTER);
                wrapper.setBorder(new EmptyBorder(0, 10, 10, 10));
                
                listPanel.add(wrapper);
            }
        }
        listPanel.revalidate();
        listPanel.repaint();
    }

    // --- CÁC HÀM HỖ TRỢ (COLLECTION & DIALOG) ---
    
    private void showCollectionMenuDialog() {
        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Collections", true);
        dialog.setSize(400, 300);
        dialog.setLocationRelativeTo(this);
        dialog.getContentPane().setBackground(new Color(240, 240, 240));
        dialog.setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(15, 0, 15, 0);
        gbc.gridx = 0;
        gbc.gridy = 0;

        JButton btnView = new JButton("View My Collections");
        styleFlowButton(btnView);
        btnView.addActionListener(e -> {
            dialog.dispose();
            showViewCollectionsDialog();
        });
        
        JButton btnNew = new JButton("Create New Collection");
        styleFlowButton(btnNew);
        btnNew.addActionListener(e -> {
            dialog.dispose();
            showCreateCollectionDialog();
        });

        dialog.add(btnView, gbc);
        gbc.gridy = 1;
        dialog.add(btnNew, gbc);
        
        dialog.setVisible(true);
    }

    private void showCreateCollectionDialog() {
        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "New Collection", true);
        dialog.setSize(400, 250);
        dialog.setLocationRelativeTo(this);
        dialog.setLayout(new GridBagLayout());

        JTextField txtName = new JTextField(20);
        txtName.setBorder(BorderFactory.createTitledBorder("Collection Name"));
        txtName.setPreferredSize(new Dimension(250, 50));
        
        JButton btnCreate = new JButton("Create");
        styleFlowButton(btnCreate);
        btnCreate.setPreferredSize(new Dimension(100, 40));
        btnCreate.setBackground(new Color(52, 152, 219));
        btnCreate.setForeground(Color.WHITE);
        
        btnCreate.addActionListener(e -> {
            if (!txtName.getText().trim().isEmpty()) {
                collectionService.createCollection(SessionManager.getInstance().getCurrentUser(), txtName.getText());
                dialog.dispose();
                showCollectionMenuDialog();
            }
        });

        dialog.add(txtName);
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridy = 1;
        gbc.insets = new Insets(20, 0, 0, 0);
        dialog.add(btnCreate, gbc);
        
        dialog.setVisible(true);
    }

    private void showViewCollectionsDialog() {
        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Your Collections", true);
        dialog.setSize(500, 600);
        dialog.setLocationRelativeTo(this);
        dialog.setLayout(new BorderLayout());
        
        JPanel content = new JPanel();
        content.setLayout(new BoxLayout(content, BoxLayout.Y_AXIS));
        content.setBackground(Color.WHITE);
        content.setBorder(new EmptyBorder(20, 20, 20, 20));
        
        selectedPanel = null;
        selectedObject = null;

        int userId = SessionManager.getInstance().getCurrentUser().getUserId();
        ArrayList<Collection> collections = collectionService.getCollectionsForUser(userId);

        if (collections.isEmpty()) {
            content.add(new JLabel("No collections found."));
        }

        for (Collection col : collections) {
            JPanel p = new JPanel(new BorderLayout());
            p.setBackground(new Color(240, 240, 240));
            p.setMaximumSize(new Dimension(Integer.MAX_VALUE, 50));
            p.setBorder(new EmptyBorder(10, 15, 10, 15));
            
            JLabel lbl = new JLabel(col.getCollectionName());
            lbl.setFont(new Font("Segoe UI", Font.BOLD, 14));
            p.add(lbl, BorderLayout.CENTER);
            
            p.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    if (selectedPanel != null) selectedPanel.setBackground(new Color(240, 240, 240));
                    if (e.getClickCount() == 2) {
                        dialog.dispose();
                        showCollectionDetailDialog(col);
                        return;
                    }
                    selectedPanel = p;
                    selectedObject = col;
                    p.setBackground(new Color(52, 152, 219)); // Highlight color
                }
            });
            
            content.add(p);
            content.add(Box.createVerticalStrut(10));
        }
        
        dialog.add(new JScrollPane(content), BorderLayout.CENTER);

        JPanel footer = new JPanel(new BorderLayout());
        footer.setBorder(new EmptyBorder(10, 20, 10, 20));

        JButton btnRen = new JButton("Rename");
        styleFlowButton(btnRen); 
        btnRen.setPreferredSize(new Dimension(100, 40));
        
        JButton btnDel = new JButton("Delete");
        styleFlowButton(btnDel); 
        btnDel.setPreferredSize(new Dimension(100, 40));
        btnDel.setForeground(Color.RED);

        btnRen.addActionListener(e -> {
            if (selectedObject instanceof Collection) {
                Collection col = (Collection) selectedObject;
                String newN = JOptionPane.showInputDialog("Rename to:", col.getCollectionName());
                if (newN != null) {
                    collectionService.renameCollection(col.getCollectionId(), newN, SessionManager.getInstance().getCurrentUser());
                    dialog.dispose();
                    showViewCollectionsDialog();
                }
            } else {
                JOptionPane.showMessageDialog(dialog, "Please select a collection.");
            }
        });

        btnDel.addActionListener(e -> {
            if (selectedObject instanceof Collection) {
                Collection col = (Collection) selectedObject;
                if (JOptionPane.showConfirmDialog(dialog, "Delete collection?") == JOptionPane.YES_OPTION) {
                    collectionService.deleteCollection(col.getCollectionId(), SessionManager.getInstance().getCurrentUser());
                    dialog.dispose();
                    showViewCollectionsDialog();
                }
            } else {
                JOptionPane.showMessageDialog(dialog, "Please select a collection.");
            }
        });

        footer.add(btnRen, BorderLayout.WEST);
        footer.add(btnDel, BorderLayout.EAST);
        dialog.add(footer, BorderLayout.SOUTH);

        dialog.setVisible(true);
    }

    private void showCollectionDetailDialog(Collection col) {
        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), col.getCollectionName(), true);
        dialog.setSize(600, 500);
        dialog.setLocationRelativeTo(this);
        dialog.setLayout(new BorderLayout());

        JPanel header = new JPanel(new FlowLayout(FlowLayout.CENTER));
        JLabel title = new JLabel(col.getCollectionName());
        title.setFont(new Font("Segoe UI", Font.BOLD, 18));
        header.add(title);
        dialog.add(header, BorderLayout.NORTH);

        JPanel listP = new JPanel();
        listP.setLayout(new BoxLayout(listP, BoxLayout.Y_AXIS));
        listP.setBackground(Color.WHITE);
        listP.setBorder(new EmptyBorder(10, 10, 10, 10));
        
        dialog.add(new JScrollPane(listP), BorderLayout.CENTER);

        selectedPanel = null;
        selectedObject = null;

        Runnable reload = () -> {
            listP.removeAll();
            ArrayList<Book> books = collectionService.getBooksInCollection(col.getCollectionId(), SessionManager.getInstance().getCurrentUser());
            
            if (books.isEmpty()) {
                JLabel empty = new JLabel("No books in this collection.");
                empty.setAlignmentX(Component.CENTER_ALIGNMENT);
                listP.add(empty);
            } else {
                for (Book b : books) {
                    JPanel p = new JPanel(new BorderLayout());
                    p.setBackground(new Color(240, 240, 240));
                    p.setMaximumSize(new Dimension(Integer.MAX_VALUE, 50));
                    p.setBorder(new EmptyBorder(5, 10, 5, 10));
                    
                    p.add(new JLabel(b.getBookTitle()), BorderLayout.CENTER);
                    
                    p.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent e) {
                            if (selectedPanel != null) selectedPanel.setBackground(new Color(240, 240, 240));
                            selectedPanel = p;
                            selectedObject = b;
                            p.setBackground(new Color(52, 152, 219));
                        }
                    });
                    
                    listP.add(p);
                    listP.add(Box.createVerticalStrut(10));
                }
            }
            listP.revalidate();
            listP.repaint();
        };
        reload.run();

        JPanel footer = new JPanel(new BorderLayout());
        footer.setBorder(new EmptyBorder(10, 20, 10, 20));

        JButton btnAdd = new JButton("Add Book");
        styleFlowButton(btnAdd);
        btnAdd.setPreferredSize(new Dimension(100, 40));
        
        JButton btnRem = new JButton("Remove Book");
        styleFlowButton(btnRem);
        btnRem.setPreferredSize(new Dimension(120, 40));

        btnAdd.addActionListener(e -> showAddBookDialog(dialog, col, reload));
        
        btnRem.addActionListener(e -> {
            if (selectedObject instanceof Book) {
                Book b = (Book) selectedObject;
                if (JOptionPane.showConfirmDialog(dialog, "Remove book from collection?") == JOptionPane.YES_OPTION) {
                    collectionService.removeBookFromCollection(b.getBookId(), col.getCollectionId(), SessionManager.getInstance().getCurrentUser());
                    reload.run();
                }
            } else {
                JOptionPane.showMessageDialog(dialog, "Select a book to remove.");
            }
        });

        footer.add(btnAdd, BorderLayout.WEST);
        footer.add(btnRem, BorderLayout.EAST);
        dialog.add(footer, BorderLayout.SOUTH);

        dialog.setVisible(true);
    }

    private void showAddBookDialog(JDialog parent, Collection col, Runnable onDone) {
        JDialog dialog = new JDialog(parent, "Add Book to Collection", true);
        dialog.setSize(500, 400);
        dialog.setLocationRelativeTo(parent);
        dialog.setLayout(new BorderLayout());
        
        JPanel searchP = new JPanel(new FlowLayout());
        JTextField txtS = new JTextField(20);
        JButton btnS = new JButton("Search");
        searchP.add(txtS);
        searchP.add(btnS);
        dialog.add(searchP, BorderLayout.NORTH);
        
        JPanel listP = new JPanel();
        listP.setLayout(new BoxLayout(listP, BoxLayout.Y_AXIS));
        listP.setBackground(Color.WHITE);
        dialog.add(new JScrollPane(listP), BorderLayout.CENTER);

        final Book[] selBook = {null};
        final JPanel[] selP = {null};

        Runnable load = () -> {
            listP.removeAll();
            String k = txtS.getText().toLowerCase();
            ArrayList<Book> filteredBooks = new ArrayList<>();
            for (Book b : currentLibraryBooks) {
                if (b.getBookTitle().toLowerCase().contains(k) || b.getAuthorName().toLowerCase().contains(k)) {
                    filteredBooks.add(b);
                }
            }
            
            if (filteredBooks.isEmpty()) {
                listP.add(new JLabel("No matching books in your Library."));
            }

            for (Book b : filteredBooks) {
                JPanel p = new JPanel(new BorderLayout());
                p.setBackground(new Color(240, 240, 240));
                p.setMaximumSize(new Dimension(Integer.MAX_VALUE, 50));
                p.setBorder(new EmptyBorder(5, 10, 5, 10));
                p.add(new JLabel(b.getBookTitle()), BorderLayout.CENTER);
                
                p.addMouseListener(new MouseAdapter() {
                    public void mouseClicked(MouseEvent e) {
                        if (selP[0] != null) selP[0].setBackground(new Color(240, 240, 240));
                        selP[0] = p;
                        selBook[0] = b;
                        p.setBackground(new Color(52, 152, 219));
                    }
                });
                
                listP.add(p);
                listP.add(Box.createVerticalStrut(5));
            }
            listP.revalidate();
            listP.repaint();
        };
        
        btnS.addActionListener(e -> load.run());
        load.run();
        
        JPanel footer = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        JButton btnAdd = new JButton("Add Selected");
        styleFlowButton(btnAdd);
        
        btnAdd.addActionListener(e -> {
            if (selBook[0] != null) {
                try {
                    collectionService.addBookToCollection(selBook[0].getBookId(), col.getCollectionId(), SessionManager.getInstance().getCurrentUser());
                    JOptionPane.showMessageDialog(dialog, "Added!");
                    onDone.run(); 
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(dialog, ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(dialog, "Select a book first.");
            }
        });
        
        footer.add(btnAdd);
        dialog.add(footer, BorderLayout.SOUTH);
        
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                onDone.run();
            }
        });
        
        dialog.setVisible(true);
    }

    // Hàm trang trí nút (dùng trong dialog)
    private void styleFlowButton(JButton btn) {
        btn.setPreferredSize(new Dimension(200, 50));
        btn.setBackground(new Color(240, 240, 240));
        btn.setFocusPainted(false);
        btn.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1, true));
    }
    
    // Hàm trang trí nút nhỏ (dùng trong list item)
    private void styleSmallButton(JButton btn) {
        btn.setBackground(new Color(220, 220, 220));
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCollections;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listPanel;
    private javax.swing.JPanel listWrapper;
    private javax.swing.JPanel pnlSearchBox;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration                   
}