/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ebookmanager.ui;

/**
 *
 * @author trank
 */
import com.ebookmanager.service.AuthenticationService;
import com.ebookmanager.ui.MainView; 
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
public class LoginAndRegister extends javax.swing.JFrame {
    
    private AuthenticationService authService = new AuthenticationService();

    /**
     * Creates new form LoginAndRegister
     */
    public LoginAndRegister() {
        initComponents();
        this.setLocationRelativeTo(null);
        mainContainer.add(pnlLogin, "LOGIN");
        mainContainer.add(pnlRegister, "REGISTER");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainContainer = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        pnlLoginLeft = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlLoginForm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLoginUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLoginPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRegisterSwitch = new javax.swing.JButton();
        pnlRegister = new javax.swing.JPanel();
        pnlRegisterLeft = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlRegisterForm = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtRegisterUser = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRegisterPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtRegisterConfirmPass = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        btnLoginSwitch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainContainer.setPreferredSize(new java.awt.Dimension(1000, 650));
        mainContainer.setLayout(new java.awt.CardLayout());

        pnlLogin.setPreferredSize(new java.awt.Dimension(1000, 650));
        pnlLogin.setLayout(new java.awt.GridLayout(1, 2));

        pnlLoginLeft.setBackground(new java.awt.Color(44, 62, 80));
        pnlLoginLeft.setPreferredSize(new java.awt.Dimension(0, 0));
        pnlLoginLeft.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-BOOK MANAGER");
        pnlLoginLeft.add(jLabel1, new java.awt.GridBagConstraints());

        pnlLogin.add(pnlLoginLeft);

        pnlLoginForm.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoginForm.setPreferredSize(new java.awt.Dimension(0, 0));
        pnlLoginForm.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome Back");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlLoginForm.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        pnlLoginForm.add(jLabel3, gridBagConstraints);

        txtLoginUser.setPreferredSize(new java.awt.Dimension(250, 40));
        txtLoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginUserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlLoginForm.add(txtLoginUser, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        pnlLoginForm.add(jLabel4, gridBagConstraints);

        txtLoginPass.setPreferredSize(new java.awt.Dimension(250, 40));
        txtLoginPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginPassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlLoginForm.add(txtLoginPass, gridBagConstraints);

        btnLogin.setBackground(new java.awt.Color(52, 152, 219));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setPreferredSize(new java.awt.Dimension(250, 40));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnlLoginForm.add(btnLogin, gridBagConstraints);

        btnRegisterSwitch.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnRegisterSwitch.setText("No account? Register here");
        btnRegisterSwitch.setBorderPainted(false);
        btnRegisterSwitch.setContentAreaFilled(false);
        btnRegisterSwitch.setFocusPainted(false);
        btnRegisterSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterSwitchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlLoginForm.add(btnRegisterSwitch, gridBagConstraints);

        pnlLogin.add(pnlLoginForm);

        mainContainer.add(pnlLogin, "card2");

        pnlRegister.setPreferredSize(new java.awt.Dimension(1000, 650));
        pnlRegister.setLayout(new java.awt.GridLayout(1, 2));

        pnlRegisterLeft.setBackground(new java.awt.Color(44, 62, 80));
        pnlRegisterLeft.setPreferredSize(new java.awt.Dimension(0, 0));
        pnlRegisterLeft.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("E-BOOK MANAGER");
        pnlRegisterLeft.add(jLabel9, new java.awt.GridBagConstraints());

        pnlRegister.add(pnlRegisterLeft);

        pnlRegisterForm.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegisterForm.setPreferredSize(new java.awt.Dimension(0, 0));
        pnlRegisterForm.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Register");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlRegisterForm.add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        pnlRegisterForm.add(jLabel11, gridBagConstraints);

        txtRegisterUser.setPreferredSize(new java.awt.Dimension(250, 40));
        txtRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterUserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlRegisterForm.add(txtRegisterUser, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        pnlRegisterForm.add(jLabel12, gridBagConstraints);

        txtRegisterPass.setPreferredSize(new java.awt.Dimension(250, 40));
        txtRegisterPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterPassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlRegisterForm.add(txtRegisterPass, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Confirm Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        pnlRegisterForm.add(jLabel5, gridBagConstraints);

        txtRegisterConfirmPass.setPreferredSize(new java.awt.Dimension(250, 40));
        txtRegisterConfirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterConfirmPassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlRegisterForm.add(txtRegisterConfirmPass, gridBagConstraints);

        btnRegister.setBackground(new java.awt.Color(52, 152, 219));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.setPreferredSize(new java.awt.Dimension(250, 40));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnlRegisterForm.add(btnRegister, gridBagConstraints);

        btnLoginSwitch.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnLoginSwitch.setText("Have an account? Login");
        btnLoginSwitch.setBorderPainted(false);
        btnLoginSwitch.setContentAreaFilled(false);
        btnLoginSwitch.setFocusPainted(false);
        btnLoginSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginSwitchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlRegisterForm.add(btnLoginSwitch, gridBagConstraints);

        pnlRegister.add(pnlRegisterForm);

        mainContainer.add(pnlRegister, "card2");

        getContentPane().add(mainContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginUserActionPerformed

    private void txtRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegisterUserActionPerformed

    private void btnLoginSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginSwitchActionPerformed
        CardLayout cl = (CardLayout) mainContainer.getLayout();
        cl.show(mainContainer, "LOGIN");
    }//GEN-LAST:event_btnLoginSwitchActionPerformed

    private void txtRegisterPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegisterPassActionPerformed

    private void txtLoginPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginPassActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            String username = txtLoginUser.getText();
            String password = new String(txtLoginPass.getPassword());

            if (username.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
                return;
            }
            authService.login(username, password);
            new MainView().setVisible(true);
            this.dispose(); 

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi đăng nhập: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterSwitchActionPerformed
        CardLayout cl = (CardLayout) mainContainer.getLayout();
        cl.show(mainContainer, "REGISTER");
    }//GEN-LAST:event_btnRegisterSwitchActionPerformed

    private void txtRegisterConfirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterConfirmPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegisterConfirmPassActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        try {
            String username = txtRegisterUser.getText();
            String password = new String(txtRegisterPass.getPassword());
            String confirm = new String(txtRegisterConfirmPass.getPassword());

            if (username.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin!");
                return;
            }
            if (!password.equals(confirm)) {
                JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không khớp!");
                return;
            }

            authService.register(username, password, confirm);
            JOptionPane.showMessageDialog(this, "Đăng ký thành công! Hãy đăng nhập.");

            
            CardLayout cl = (CardLayout) mainContainer.getLayout();
            cl.show(mainContainer, "LOGIN");

            
            txtRegisterUser.setText("");
            txtRegisterPass.setText("");
            txtRegisterConfirmPass.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi đăng ký: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace(); 
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginAndRegister().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginSwitch;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterSwitch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLoginForm;
    private javax.swing.JPanel pnlLoginLeft;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JPanel pnlRegisterForm;
    private javax.swing.JPanel pnlRegisterLeft;
    private javax.swing.JPasswordField txtLoginPass;
    private javax.swing.JTextField txtLoginUser;
    private javax.swing.JPasswordField txtRegisterConfirmPass;
    private javax.swing.JPasswordField txtRegisterPass;
    private javax.swing.JTextField txtRegisterUser;
    // End of variables declaration//GEN-END:variables
}
