/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ebookmanager.ui;

import javax.swing.JOptionPane;
import com.ebookmanager.ui.MainView;
import java.awt.Color;
/**
 *
 * @author trank
 */
// SỬA LỖI 1: Phải là javax.swing.JFrame
public class LoginAndRegister extends javax.swing.JFrame {

    // Khai báo AuthenticationService
    private com.ebookmanager.service.AuthenticationService authService = new com.ebookmanager.service.AuthenticationService();

    public LoginAndRegister() {
        initComponents();
        Color colorBlue = new Color(52, 152, 219); 
        
        // 1. Cấu hình nút chuyển trang (Link) cho trong suốt và màu xanh
        // Bên Login
        btnLogin.setContentAreaFilled(false);
        btnLogin.setBorder(null);
        btnLogin.setForeground(colorBlue);
        
        // Bên Register
        btnLoginSwitch.setContentAreaFilled(false);
        btnLoginSwitch.setBorder(null);
        btnLoginSwitch.setForeground(colorBlue);
        
        // 2. Cấu hình nút bấm chính (Nền xanh)
        // Bên Login (Nút tên ngược: btnRegisterSwitch)
        btnRegisterSwitch.setBackground(colorBlue);
        btnRegisterSwitch.setForeground(Color.WHITE);
        
        // Bên Register
        btnRegister.setBackground(colorBlue);
        btnRegister.setForeground(Color.WHITE);
        
        // Căn giữa màn hình
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainContainer = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLoginUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLoginPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRegisterSwitch = new javax.swing.JButton();
        pnlRegister = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRegisterUser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRegisterPass = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        btnLoginSwitch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtRegisterConfirmPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        mainContainer.setLayout(new java.awt.CardLayout());

        pnlLogin.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-BOOK MANAGER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0; 
        gridBagConstraints.weighty = 1.0; 
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER; 
        jPanel2.add(jLabel1, gridBagConstraints);

        pnlLogin.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Welcome Back");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 40, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 10, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        txtLoginUser.setPreferredSize(new java.awt.Dimension(250, 40));
        txtLoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginUserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel3.add(txtLoginUser, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel3.add(jLabel4, gridBagConstraints);

        txtLoginPass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtLoginPass.setPreferredSize(new java.awt.Dimension(250, 40));
        txtLoginPass.setVerifyInputWhenFocusTarget(false);
        txtLoginPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginPassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel3.add(txtLoginPass, gridBagConstraints);

        btnLogin.setForeground(new java.awt.Color(52, 152, 219));
        btnLogin.setText("No account? Register here");
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogin.setContentAreaFilled(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel3.add(btnLogin, gridBagConstraints);

        btnRegisterSwitch.setBackground(new java.awt.Color(52, 152, 219));
        btnRegisterSwitch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegisterSwitch.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterSwitch.setText("LOGIN");
        btnRegisterSwitch.setPreferredSize(new java.awt.Dimension(250, 40));
        btnRegisterSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterSwitchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel3.add(btnRegisterSwitch, gridBagConstraints);

        pnlLogin.add(jPanel3);
        mainContainer.add(pnlLogin, "LOGIN");

        pnlRegister.setLayout(new java.awt.GridLayout(1, 2));

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-BOOK MANAGER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        jPanel4.add(jLabel5, gridBagConstraints);


        pnlRegister.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Create Account");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        jPanel5.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel5.add(jLabel7, gridBagConstraints);

        txtRegisterUser.setPreferredSize(new java.awt.Dimension(250, 40));
        txtRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterUserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel5.add(txtRegisterUser, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel5.add(jLabel8, gridBagConstraints);

        txtRegisterPass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtRegisterPass.setPreferredSize(new java.awt.Dimension(250, 40));
        txtRegisterPass.setVerifyInputWhenFocusTarget(false);
        txtRegisterPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterPassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel5.add(txtRegisterPass, gridBagConstraints);

        btnRegister.setBackground(new java.awt.Color(51, 102, 255));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.setPreferredSize(new java.awt.Dimension(250, 40));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel5.add(btnRegister, gridBagConstraints);

        btnLoginSwitch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLoginSwitch.setForeground(new java.awt.Color(51, 102, 255));
        btnLoginSwitch.setText("Have an account? Login");
        btnLoginSwitch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLoginSwitch.setBorderPainted(false);
        btnLoginSwitch.setContentAreaFilled(false);
        btnLoginSwitch.setPreferredSize(new java.awt.Dimension(250, 40));
        btnLoginSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginSwitchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel5.add(btnLoginSwitch, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Confirm Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel5.add(jLabel9, gridBagConstraints);

        txtRegisterConfirmPass.setPreferredSize(new java.awt.Dimension(250, 40));
        txtRegisterConfirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterConfirmPassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel5.add(txtRegisterConfirmPass, gridBagConstraints);

        pnlRegister.add(jPanel5);

        // SỬA LỖI 2: Đặt tên thẻ đúng là REGISTER
        mainContainer.add(pnlRegister, "REGISTER");

        getContentPane().add(mainContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    private void exitForm(java.awt.event.WindowEvent evt) {                          
        System.exit(0);
    }                         

    // LOGIC: Nút btnLogin (No account...) -> Chuyển sang REGISTER
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {                                         
        java.awt.CardLayout cl = (java.awt.CardLayout) mainContainer.getLayout();
        cl.show(mainContainer, "REGISTER");
    }                                        

    // LOGIC: Nút btnRegisterSwitch (Nút LOGIN to) -> Thực hiện Đăng nhập
    private void btnRegisterSwitchActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        try {
            String username = txtLoginUser.getText();
            String password = new String(txtLoginPass.getPassword()); 

            authService.login(username, password);
            new MainView().setVisible(true);
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                                 

    // LOGIC: Nút btnLoginSwitch (Have account...) -> Quay về LOGIN
    private void btnLoginSwitchActionPerformed(java.awt.event.ActionEvent evt) {                                               
        java.awt.CardLayout cl = (java.awt.CardLayout) mainContainer.getLayout();
        cl.show(mainContainer, "LOGIN");
    }                                              

    // LOGIC: Nút btnRegister (Nút REGISTER to) -> Thực hiện Đăng ký
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {                                            
        try {
            String username = txtRegisterUser.getText();
            String password = new String(txtRegisterPass.getPassword());
            String confirm = new String(txtRegisterConfirmPass.getPassword());

            authService.register(username, password, confirm);

            JOptionPane.showMessageDialog(this, "Registration Successful! Please Login.");

            java.awt.CardLayout cl = (java.awt.CardLayout) mainContainer.getLayout();
            cl.show(mainContainer, "LOGIN");
            
            txtRegisterUser.setText("");
            txtRegisterPass.setText("");
            txtRegisterConfirmPass.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Registration Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                           

    private void txtLoginPassActionPerformed(java.awt.event.ActionEvent evt) {}                                            
    private void txtRegisterPassActionPerformed(java.awt.event.ActionEvent evt) {}                                               
    private void txtRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {}                                               
    private void txtLoginUserActionPerformed(java.awt.event.ActionEvent evt) {}                                            
    private void txtRegisterConfirmPassActionPerformed(java.awt.event.ActionEvent evt) {}                                                       

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAndRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginSwitch;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterSwitch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JPasswordField txtLoginPass;
    private javax.swing.JTextField txtLoginUser;
    private javax.swing.JPasswordField txtRegisterConfirmPass;
    private javax.swing.JPasswordField txtRegisterPass;
    private javax.swing.JTextField txtRegisterUser;
    // End of variables declaration                   
}