/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ebookmanager.ui;

/**
 *
 * @author trank
 */
import com.ebookmanager.model.Book;
import com.ebookmanager.model.BookProgress;
import com.ebookmanager.model.Bookmark;
import com.ebookmanager.service.*;
import com.ebookmanager.util.SessionManager;
import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.util.ArrayList;
import javax.swing.*;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;
public class ReadingPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReadingPanel
     */
    private Book book;
    private MainView mainView;
    private boolean isPreview;
    
    
    private BookProgressService progressService;
    private BookmarkService bookmarkService;
    
    
    private int currentPage = 0;
    private int totalPages = 0;
    private PDDocument document;
    private PDFRenderer pdfRenderer;
    public ReadingPanel(Book book, MainView mainView, boolean isPreview) {
        this.book = book;
        this.mainView = mainView;
        this.isPreview = isPreview;
        
        this.progressService = new BookProgressService();
        this.bookmarkService = new BookmarkService();
        initComponents();
        applyCustomStyles(); 
        loadBookData();      
    }
    public ReadingPanel(Book book, MainView mainView) {
        this(book, mainView, false);
    }
    public ReadingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblPageInfo = new javax.swing.JLabel();
        btnBookmarks = new javax.swing.JButton();
        scrollPaneBook = new javax.swing.JScrollPane();
        lblPageImage = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setBackground(new java.awt.Color(50, 50, 50));
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setLayout(new java.awt.BorderLayout());

        pnlTop.setOpaque(false);
        pnlTop.setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlTop.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setOpaque(false);

        lblPageInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPageInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblPageInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPageInfo.setText("Loading...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblPageInfo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblPageInfo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlTop.add(jPanel2, java.awt.BorderLayout.CENTER);

        btnBookmarks.setText("Bookmarks");
        btnBookmarks.setToolTipText("");
        btnBookmarks.setPreferredSize(new java.awt.Dimension(110, 35));
        btnBookmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookmarksActionPerformed(evt);
            }
        });
        pnlTop.add(btnBookmarks, java.awt.BorderLayout.EAST);

        add(pnlTop, java.awt.BorderLayout.NORTH);

        scrollPaneBook.setBorder(null);
        add(scrollPaneBook, java.awt.BorderLayout.CENTER);

        lblPageImage.setBackground(new java.awt.Color(80, 80, 80));
        lblPageImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPageImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblPageImage.setOpaque(true);
        add(lblPageImage, java.awt.BorderLayout.CENTER);

        pnlBottom.setOpaque(false);
        pnlBottom.setLayout(new java.awt.BorderLayout());

        btnPrev.setBackground(new java.awt.Color(51, 204, 255));
        btnPrev.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev.setText("Prev Page");
        btnPrev.setPreferredSize(new java.awt.Dimension(120, 45));
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        pnlBottom.add(btnPrev, java.awt.BorderLayout.WEST);

        btnNext.setBackground(new java.awt.Color(51, 204, 255));
        btnNext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Next Page");
        btnNext.setPreferredSize(new java.awt.Dimension(120, 45));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlBottom.add(btnNext, java.awt.BorderLayout.EAST);

        jPanel3.setOpaque(false);

        btnClose.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClose.setText("Close Reader");
        btnClose.setPreferredSize(new java.awt.Dimension(150, 45));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlBottom.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(pnlBottom, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadBookData() {
        
        lblPageInfo.setText("Loading...");
        
        new Thread(() -> {
            try {
                BookService bs = new BookService();
                InputStream is = bs.readBook(book);
                
                if (is == null) {
                    SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "File sách không tồn tại!"));
                    return;
                }

                
                PDDocument doc = PDDocument.load(is);
                document = doc;
                pdfRenderer = new PDFRenderer(document);
                totalPages = document.getNumberOfPages();
                
                
                if (!isPreview) {
                    int userId = SessionManager.getInstance().getCurrentUser().getUserId();
                    BookProgress bp = progressService.getBookProgress(userId, book.getBookId());
                    if (bp != null && bp.getCurrentPage() != null) {
                        currentPage = Math.min(bp.getCurrentPage(), totalPages - 1);
                    }
                }
                
                
                SwingUtilities.invokeLater(this::renderCurrentPage);
                
            } catch (Exception e) {
                e.printStackTrace();
                SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "Lỗi tải PDF: " + e.getMessage()));
            }
        }).start();
    }

    
    private void renderCurrentPage() {
        if (document == null) return;
        try {
            
            float scale = 1.5f; 
            BufferedImage image = pdfRenderer.renderImage(currentPage, scale);
            
            
            lblPageImage.setIcon(new ImageIcon(image));
            lblPageImage.setText(""); 
            
            
            lblPageInfo.setText("Page " + (currentPage + 1) + " / " + totalPages);
            
            
            scrollPaneBook.getVerticalScrollBar().setValue(0);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    
    private void changePage(int delta) {
        int newPage = currentPage + delta;
        if (newPage >= 0 && newPage < totalPages) {
            currentPage = newPage;
            renderCurrentPage();
        }
    }

    
    private void closeBook() {
        try {
            if (document != null) document.close();
            
            if (isPreview) {
                mainView.goBackToCommunity(); 
            } else {
                int userId = SessionManager.getInstance().getCurrentUser().getUserId();
                if (!progressService.isBookInLibrary(userId, book.getBookId())) {
                    progressService.addBookToLibrary(userId, book.getBookId());
                }
                progressService.updateBookProgress(userId, book.getBookId(), currentPage, 0);
                
                mainView.goBackToLibrary(); 
            }
        } catch (Exception e) { e.printStackTrace(); }
    }

    
    private void showBookmarkOptionMenu() {
        JPopupMenu menu = new JPopupMenu();
        
        JMenuItem itemView = new JMenuItem("View All Bookmarks");
        itemView.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        itemView.addActionListener(e -> showViewAllBookmarksDialog());
        
        JMenuItem itemNew = new JMenuItem("Bookmark This Page");
        itemNew.setFont(new Font("Segoe UI", Font.BOLD, 14));
        itemNew.addActionListener(e -> showCreateBookmarkDialog());
        
        menu.add(itemView);
        menu.addSeparator();
        menu.add(itemNew);
        menu.show(btnBookmarks, 0, btnBookmarks.getHeight());
    }
    private void showCreateBookmarkDialog() {
        if (isPreview) {
            JOptionPane.showMessageDialog(this, "Please add to library to use bookmarks.");
            return;
        }
        String name = JOptionPane.showInputDialog(this, "Name for Page " + (currentPage + 1) + ":");
        if (name != null && !name.trim().isEmpty()) {
            bookmarkService.createBookmark(SessionManager.getInstance().getCurrentUser().getUserId(), 
                    book.getBookId(), String.valueOf(currentPage), name);
            JOptionPane.showMessageDialog(this, "Saved!");
        }
    }
    private void showViewAllBookmarksDialog() {
        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Bookmarks", true);
        dialog.setSize(350, 400);
        dialog.setLocationRelativeTo(this);
        
        JPanel listPanel = new JPanel();
        listPanel.setLayout(new BoxLayout(listPanel, BoxLayout.Y_AXIS));
        listPanel.setBackground(Color.WHITE);
        
        int userId = SessionManager.getInstance().getCurrentUser().getUserId();
        ArrayList<Bookmark> bms = bookmarkService.getBookmarksForBook(userId, book.getBookId());

        if (bms.isEmpty()) {
            listPanel.add(new JLabel("No bookmarks found."));
        } else {
            for (Bookmark bm : bms) {
                JPanel row = new JPanel(new BorderLayout());
                row.setBackground(new Color(245, 245, 245));
                row.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
                row.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 5));
                
                JLabel lblName = new JLabel(bm.getName() + " (Pg " + (Integer.parseInt(bm.getLocationData()) + 1) + ")");
                lblName.setCursor(new Cursor(Cursor.HAND_CURSOR));
                lblName.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        currentPage = Integer.parseInt(bm.getLocationData());
                        renderCurrentPage();
                        dialog.dispose();
                    }
                });
                
                JButton btnDel = new JButton("x");
                btnDel.setForeground(Color.RED);
                btnDel.setBorderPainted(false);
                btnDel.setContentAreaFilled(false);
                btnDel.addActionListener(e -> {
                    bookmarkService.deleteBookmark(bm.getBookmarkId());
                    dialog.dispose();
                    showViewAllBookmarksDialog();
                });
                
                row.add(lblName, BorderLayout.CENTER);
                row.add(btnDel, BorderLayout.EAST);
                listPanel.add(row);
                listPanel.add(Box.createVerticalStrut(5));
            }
        }
        dialog.add(new JScrollPane(listPanel));
        dialog.setVisible(true);
    }

    
    private void applyCustomStyles() {
        
        scrollPaneBook.getVerticalScrollBar().setUnitIncrement(20);
        btnBookmarks.setFocusPainted(false);
        btnBookmarks.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        changePage(-1);
    }//GEN-LAST:event_btnPrevActionPerformed
    
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        closeBook(); 
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        changePage(1); 
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBookmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookmarksActionPerformed
        showBookmarkOptionMenu();
    }//GEN-LAST:event_btnBookmarksActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookmarks;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblPageImage;
    private javax.swing.JLabel lblPageInfo;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JScrollPane scrollPaneBook;
    // End of variables declaration//GEN-END:variables
}
